/**
 * Sample data for testing price visualization components
 */

import { PriceData, PriceTrend, DiscountData, PriceHeatmapData, PriceAnalytics } from './types';

// Sample Price Data
export const samplePriceData: PriceData[] = [
  {
    id: '1',
    productId: 'laptop001',
    productName: 'Dell Inspiron 15',
    productNameSr: 'Dell Inspiron 15',
    retailer: 'gigatron',
    retailerName: 'Gigatron',
    price: 89999,
    originalPrice: 99999,
    currency: 'RSD',
    discount: 10,
    category: 'Electronics',
    categorySr: 'Електроника',
    subcategory: 'Laptops',
    subcategorySr: 'Лаптоп рачунари',
    brand: 'Dell',
    availability: 'in_stock',
    location: 'Belgrade',
    locationSr: 'Београд',
    timestamp: '2024-01-15T10:00:00Z',
    imageUrl: 'https://example.com/laptop1.jpg',
    description: '15.6" laptop with Intel i5 processor',
    descriptionSr: '15.6" лаптоп са Intel i5 процесором',
  },
  {
    id: '2',
    productId: 'laptop001',
    productName: 'Dell Inspiron 15',
    productNameSr: 'Dell Inspiron 15',
    retailer: 'winwin',
    retailerName: 'WinWin',
    price: 87999,
    originalPrice: 98999,
    currency: 'RSD',
    discount: 11,
    category: 'Electronics',
    categorySr: 'Електроника',
    subcategory: 'Laptops',
    subcategorySr: 'Лаптоп рачунари',
    brand: 'Dell',
    availability: 'limited',
    location: 'Novi Sad',
    locationSr: 'Нови Сад',
    timestamp: '2024-01-15T10:00:00Z',
    imageUrl: 'https://example.com/laptop1.jpg',
  },
  {
    id: '3',
    productId: 'smartphone001',
    productName: 'Samsung Galaxy A54',
    productNameSr: 'Samsung Galaxy A54',
    retailer: 'gigatron',
    retailerName: 'Gigatron',
    price: 64999,
    currency: 'RSD',
    discount: 15,
    category: 'Electronics',
    categorySr: 'Електроника',
    subcategory: 'Smartphones',
    subcategorySr: 'Смартфони',
    brand: 'Samsung',
    availability: 'in_stock',
    location: 'Belgrade',
    locationSr: 'Београд',
    timestamp: '2024-01-15T10:00:00Z',
    imageUrl: 'https://example.com/phone1.jpg',
    description: '6.4" smartphone with 128GB storage',
    descriptionSr: '6.4" смартфон са 128GB меморије',
  },
  {
    id: '4',
    productId: 'smartphone001',
    productName: 'Samsung Galaxy A54',
    productNameSr: 'Samsung Galaxy A54',
    retailer: 'tmobile',
    retailerName: 'T-Mobile',
    price: 67999,
    currency: 'RSD',
    discount: 10,
    category: 'Electronics',
    categorySr: 'Електроника',
    subcategory: 'Smartphones',
    subcategorySr: 'Смартфони',
    brand: 'Samsung',
    availability: 'in_stock',
    location: 'Belgrade',
    locationSr: 'Београд',
    timestamp: '2024-01-15T10:00:00Z',
    imageUrl: 'https://example.com/phone1.jpg',
  },
  {
    id: '5',
    productId: 'tv001',
    productName: 'LG 55" OLED TV',
    productNameSr: 'LG 55" OLED TV',
    retailer: 'gigatron',
    retailerName: 'Gigatron',
    price: 149999,
    currency: 'RSD',
    discount: 20,
    category: 'Electronics',
    categorySr: 'Електроника',
    subcategory: 'TVs',
    subcategorySr: 'Телвизори',
    brand: 'LG',
    availability: 'in_stock',
    location: 'Belgrade',
    locationSr: 'Београд',
    timestamp: '2024-01-15T10:00:00Z',
    imageUrl: 'https://example.com/tv1.jpg',
  },
  {
    id: '6',
    productId: 'groceries001',
    productName: 'Domestic Apples 1kg',
    productNameSr: 'Домаће јабуке 1кг',
    retailer: 'maxi',
    retailerName: 'Maxi',
    price: 250,
    currency: 'RSD',
    category: 'Groceries',
    categorySr: 'Прехрамбени производи',
    subcategory: 'Fruits',
    subcategorySr: 'Воће',
    unit: 'kg',
    quantity: 1,
    pricePerUnit: 250,
    availability: 'in_stock',
    location: 'Belgrade',
    locationSr: 'Београд',
    timestamp: '2024-01-15T10:00:00Z',
  },
  {
    id: '7',
    productId: 'groceries001',
    productName: 'Domestic Apples 1kg',
    productNameSr: 'Домаће јабуке 1кг',
    retailer: 'idea',
    retailerName: 'Idea',
    price: 245,
    currency: 'RSD',
    discount: 5,
    category: 'Groceries',
    categorySr: 'Прехрамбени производи',
    subcategory: 'Fruits',
    subcategorySr: 'Воће',
    unit: 'kg',
    quantity: 1,
    pricePerUnit: 245,
    availability: 'in_stock',
    location: 'Belgrade',
    locationSr: 'Београд',
    timestamp: '2024-01-15T10:00:00Z',
  },
  {
    id: '8',
    productId: 'fashion001',
    productName: 'Nike Air Max 90',
    productNameSr: 'Nike Air Max 90',
    retailer: 'sportvision',
    retailerName: 'Sport Vision',
    price: 12999,
    originalPrice: 15999,
    currency: 'RSD',
    discount: 19,
    category: 'Fashion',
    categorySr: 'Мода',
    subcategory: 'Footwear',
    subcategorySr: 'Обућа',
    brand: 'Nike',
    availability: 'limited',
    location: 'Belgrade',
    locationSr: 'Београд',
    timestamp: '2024-01-15T10:00:00Z',
    imageUrl: 'https://example.com/shoes1.jpg',
  },
];

// Sample Price Trend Data
export const sampleTrendData: PriceTrend[] = [
  {
    productId: 'laptop001',
    productName: 'Dell Inspiron 15',
    productNameSr: 'Dell Inspiron 15',
    retailer: 'gigatron',
    retailerName: 'Gigatron',
    category: 'Electronics',
    categorySr: 'Електроника',
    dataPoints: [
      { date: '2024-01-01', price: 99999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-02', price: 97999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-03', price: 95999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-04', price: 93999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-05', price: 91999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-06', price: 90999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-07', price: 89999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-08', price: 88999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-09', price: 88999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-10', price: 89999, currency: 'RSD', availability: 'in_stock' },
    ],
  },
  {
    productId: 'smartphone001',
    productName: 'Samsung Galaxy A54',
    productNameSr: 'Samsung Galaxy A54',
    retailer: 'gigatron',
    retailerName: 'Gigatron',
    category: 'Electronics',
    categorySr: 'Електроника',
    dataPoints: [
      { date: '2024-01-01', price: 74999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-02', price: 73999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-03', price: 72999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-04', price: 71999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-05', price: 69999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-06', price: 67999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-07', price: 65999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-08', price: 64999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-09', price: 64999, currency: 'RSD', availability: 'in_stock' },
      { date: '2024-01-10', price: 64999, currency: 'RSD', availability: 'in_stock' },
    ],
  },
];

// Sample Discount Data
export const sampleDiscountData: DiscountData[] = [
  {
    id: 'disc1',
    productId: 'laptop001',
    productName: 'Dell Inspiron 15',
    productNameSr: 'Dell Inspiron 15',
    retailer: 'gigatron',
    retailerName: 'Gigatron',
    originalPrice: 99999,
    currentPrice: 89999,
    discountAmount: 10000,
    discountPercentage: 10,
    currency: 'RSD',
    category: 'Electronics',
    categorySr: 'Електроника',
    validUntil: '2024-01-31T23:59:59Z',
    discountType: 'percentage',
    tags: ['flash_sale', 'electronics'],
  },
  {
    id: 'disc2',
    productId: 'smartphone001',
    productName: 'Samsung Galaxy A54',
    productNameSr: 'Samsung Galaxy A54',
    retailer: 'gigatron',
    retailerName: 'Gigatron',
    originalPrice: 74999,
    currentPrice: 64999,
    discountAmount: 10000,
    discountPercentage: 13,
    currency: 'RSD',
    category: 'Electronics',
    categorySr: 'Електроника',
    validUntil: '2024-01-25T23:59:59Z',
    discountType: 'special_offer',
    tags: ['smartphones', 'samsung'],
  },
  {
    id: 'disc3',
    productId: 'fashion001',
    productName: 'Nike Air Max 90',
    productNameSr: 'Nike Air Max 90',
    retailer: 'sportvision',
    retailerName: 'Sport Vision',
    originalPrice: 15999,
    currentPrice: 12999,
    discountAmount: 3000,
    discountPercentage: 19,
    currency: 'RSD',
    category: 'Fashion',
    categorySr: 'Мода',
    validUntil: '2024-01-20T23:59:59Z',
    discountType: 'percentage',
    tags: ['footwear', 'nike', 'sale'],
  },
  {
    id: 'disc4',
    productId: 'groceries001',
    productName: 'Domestic Apples 1kg',
    productNameSr: 'Домаће јабуке 1кг',
    retailer: 'idea',
    retailerName: 'Idea',
    originalPrice: 259,
    currentPrice: 245,
    discountAmount: 14,
    discountPercentage: 5,
    currency: 'RSD',
    category: 'Groceries',
    categorySr: 'Прехрамбени производи',
    validUntil: '2024-01-18T23:59:59Z',
    discountType: 'fixed',
    tags: ['fruits', 'domestic', 'fresh'],
  },
];

// Sample Heatmap Data
export const sampleHeatmapData: PriceHeatmapData[] = [
  {
    category: 'Electronics',
    categorySr: 'Електроника',
    retailer: 'Gigatron',
    retailerName: 'Gigatron',
    avgPrice: 89999,
    minPrice: 64999,
    maxPrice: 149999,
    priceChange: -5000,
    priceChangePercentage: -5.3,
    productCount: 45,
    currency: 'RSD',
    lastUpdated: '2024-01-15T10:00:00Z',
  },
  {
    category: 'Electronics',
    categorySr: 'Електроника',
    retailer: 'WinWin',
    retailerName: 'WinWin',
    avgPrice: 87999,
    minPrice: 62999,
    maxPrice: 139999,
    priceChange: -2000,
    priceChangePercentage: -2.2,
    productCount: 38,
    currency: 'RSD',
    lastUpdated: '2024-01-15T10:00:00Z',
  },
  {
    category: 'Electronics',
    categorySr: 'Електроника',
    retailer: 'T-Mobile',
    retailerName: 'T-Mobile',
    avgPrice: 67999,
    minPrice: 49999,
    maxPrice: 99999,
    priceChange: 1000,
    priceChangePercentage: 1.5,
    productCount: 22,
    currency: 'RSD',
    lastUpdated: '2024-01-15T10:00:00Z',
  },
  {
    category: 'Fashion',
    categorySr: 'Мода',
    retailer: 'Sport Vision',
    retailerName: 'Sport Vision',
    avgPrice: 8999,
    minPrice: 2999,
    maxPrice: 19999,
    priceChange: -500,
    priceChangePercentage: -5.3,
    productCount: 67,
    currency: 'RSD',
    lastUpdated: '2024-01-15T10:00:00Z',
  },
  {
    category: 'Fashion',
    categorySr: 'Мода',
    retailer: 'Gigatron',
    retailerName: 'Gigatron',
    avgPrice: 6999,
    minPrice: 1999,
    maxPrice: 15999,
    priceChange: -300,
    priceChangePercentage: -4.1,
    productCount: 34,
    currency: 'RSD',
    lastUpdated: '2024-01-15T10:00:00Z',
  },
  {
    category: 'Groceries',
    categorySr: 'Прехрамбени производи',
    retailer: 'Maxi',
    retailerName: 'Maxi',
    avgPrice: 350,
    minPrice: 50,
    maxPrice: 2500,
    priceChange: 15,
    priceChangePercentage: 4.5,
    productCount: 234,
    currency: 'RSD',
    lastUpdated: '2024-01-15T10:00:00Z',
  },
  {
    category: 'Groceries',
    categorySr: 'Прехрамбени производи',
    retailer: 'Idea',
    retailerName: 'Idea',
    avgPrice: 345,
    minPrice: 45,
    maxPrice: 2450,
    priceChange: 10,
    priceChangePercentage: 3.0,
    productCount: 198,
    currency: 'RSD',
    lastUpdated: '2024-01-15T10:00:00Z',
  },
];

// Sample Analytics Data
export const sampleAnalytics: PriceAnalytics = {
  totalProducts: 542,
  totalRetailers: 8,
  averagePrice: 15432.50,
  averageDiscount: 12.5,
  priceRanges: {
    budget: 1000,
    midRange: 10000,
    premium: 50000,
  },
  topCategories: [
    { category: 'Electronics', categorySr: 'Електроника', productCount: 156, avgPrice: 45678.90 },
    { category: 'Fashion', categorySr: 'Мода', productCount: 234, avgPrice: 5678.45 },
    { category: 'Groceries', categorySr: 'Прехрамбени производи', productCount: 432, avgPrice: 234.56 },
    { category: 'Home & Garden', categorySr: 'Кућа и башта', productCount: 89, avgPrice: 3456.78 },
    { category: 'Sports', categorySr: 'Спорт', productCount: 67, avgPrice: 7890.12 },
  ],
  topRetailers: [
    { retailer: 'Gigatron', retailerName: 'Gigatron', productCount: 234, avgPrice: 34567.89 },
    { retailer: 'Maxi', retailerName: 'Maxi', productCount: 198, avgPrice: 345.67 },
    { retailer: 'WinWin', retailerName: 'WinWin', productCount: 167, avgPrice: 23456.78 },
    { retailer: 'Idea', retailerName: 'Idea', productCount: 145, avgPrice: 234.56 },
    { retailer: 'Sport Vision', retailerName: 'Sport Vision', productCount: 123, avgPrice: 6789.01 },
  ],
};

// Sample categories and retailers for filters
export const sampleCategories = [
  'Electronics',
  'Електроника',
  'Fashion',
  'Мода',
  'Groceries',
  'Прехрамбени производи',
  'Home & Garden',
  'Кућа и башта',
  'Sports',
  'Спорт',
  'Books',
  'Књиге',
  'Toys',
  'Играчке',
];

export const sampleRetailers = [
  'Gigatron',
  'WinWin',
  'Maxi',
  'Idea',
  'T-Mobile',
  'A1',
  'Sport Vision',
  'Gigatron Go',
  'Lilly',
  'Tehnomanija',
];

// Generate large dataset for testing performance
export const generateLargeDataset = (count: number): PriceData[] => {
  const products = ['Laptop', 'Smartphone', 'TV', 'Headphones', 'Tablet'];
  const brands = ['Dell', 'Samsung', 'LG', 'Sony', 'Apple', 'HP'];
  const retailers = ['Gigatron', 'WinWin', 'Maxi', 'Idea', 'T-Mobile'];
  const categories = ['Electronics', 'Fashion', 'Groceries', 'Home & Garden'];

  const data: PriceData[] = [];

  for (let i = 0; i < count; i++) {
    const product = products[Math.floor(Math.random() * products.length)];
    const brand = brands[Math.floor(Math.random() * brands.length)];
    const retailer = retailers[Math.floor(Math.random() * retailers.length)];
    const category = categories[Math.floor(Math.random() * categories.length)];

    data.push({
      id: `item_${i}`,
      productId: `${product.toLowerCase().replace(' ', '_')}_${Math.floor(Math.random() * 1000)}`,
      productName: `${brand} ${product}`,
      productNameSr: `${brand} ${product}`,
      retailer: retailer.toLowerCase().replace(' ', '_'),
      retailerName: retailer,
      price: Math.floor(Math.random() * 100000) + 1000,
      currency: 'RSD',
      discount: Math.floor(Math.random() * 30),
      category,
      categorySr: category,
      brand,
      availability: Math.random() > 0.1 ? 'in_stock' : Math.random() > 0.5 ? 'limited' : 'out_of_stock',
      timestamp: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
    });
  }

  return data;
};